spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fly
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yyl.flyplus.model

